apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: elasticsearch
    port: 9200
    targetPort: 9200
  selector:
    service: elasticsearch
  type: LoadBalancer
