apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: graylog
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: graylog
    spec:
      containers:
      - env:
        - name: GRAYLOG_WEB_ENDPOINT_URI
          value: http://set-your-graylog-host-here/api
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://set-your-elasticsearch-host-here:9200
        - name: GRAYLOG_PASSWORD_SECRET
          value: Some_secret_password_321
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: A270CD4BF0378870F296EAB1F8CC52E24D88CE7A2513A57F4CABD9272D097178
        image: graylog2/server:2.4.3-1
        name: graylog
        ports:
        - containerPort: 9000
        - containerPort: 12201
        resources: {}
      restartPolicy: Always
status: {}
