apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: graylog
  name: graylog
spec:
  ports:
  - name: "Port out"
    port: 80
    targetPort: 9000
  - name: "Port Message"
    port: 12201
    targetPort: 12201
  selector:
    service: graylog
  type: LoadBalancer
